### PR TITLE
Added https port to st2web service if ssl = true

### PR DESCRIPTION
**Pull request by sandesvitor**
## Description

Adding https port to st2web service if .Values.st2web.service.ssl equals `true`. .Values.st2web.service.ssl defaults to `false` for backward compatibility.

### CODE REVIEW

**Comment by cognifloyd** [comment]
I did something similar in #264. Do you need to expose both http and https? Or would #264 meet your needs?

**Comment by sandesvitor** [comment]
Hey @cognifloyd ! Yeah, #264 meet our needs =)

Thanks! May I close this PR?

**Comment by cognifloyd** [comment]
Cool. Let's leave this open until @armab has time to take a look. I don't know which approach (something like this one or #264) he would prefer.

**Comment by cognifloyd** [comment]
Closing this in favor of #264 which Eugen approved and I merged.

**Pull request closed without merging**
