### PR TITLE
Added toggling of etcd-operator as a coordination backend

### PR DESCRIPTION
**Pull request by rrahman-nv**
Added toggling of etcd-operator as a coordination backend

### CODE REVIEW

**Comment by armab** [comment]
Somewhat related to https://github.com/StackStorm/stackstorm-ha/issues/94 and https://github.com/StackStorm/st2-dockerfiles/pull/25

And so this PR allows someone to disable etcd-operator deployment in K8s cluster and use their own Redis instance for coordination backend. cc @trstruth you might be interested. 
This is somewhat similar to using custom RabbitMQ and MongoDB clusters outside of K8s deployment.

**Comment by wantdrink** [comment]
Wonderful PR. Thanks a lot @rrahman-nv  & @armab , that really helps.
A simple question: can I configure the redis 5.0 with sentinels and configure the cluster-like URL in st2.conf?

**Comment by armab** [comment]
Sure, that could be configured.
We're using tooz library for st2 `[coordination]` which abstracts common functionality for different backends.

For Redis cluster connection string examples see:
https://github.com/openstack/tooz/blob/master/tooz/drivers/redis.py

**Comment by wantdrink** [comment]
@armab  awesome! Thanks a lot.

**Pull request merged**
